"""
The two remediation paths:
  - safe drift  -> commit reconciled manifests to a branch + open a GitHub PR
  - risky drift -> post a formatted alert to Slack for a human to review
"""

import subprocess
import time
import requests


def open_remediation_pr(
    diff_summary: str,
    reasoning: str,
    git_local_path: str,
    github_repo: str,
    github_token: str,
    base_branch: str,
) -> str:
    """
    Assumes git_local_path is a clean checkout of github_repo that already
    reflects the CURRENT (drifted) manifests you want to commit as the new
    desired state reconciling with reality -- adjust to your actual workflow
    (e.g. you may instead want to revert the cluster, not the repo).
    """
    branch_name = f"drift-fix-{int(time.time())}"

    subprocess.run(["git", "-C", git_local_path, "checkout", base_branch], check=True)
    subprocess.run(["git", "-C", git_local_path, "pull"], check=True)
    subprocess.run(["git", "-C", git_local_path, "checkout", "-b", branch_name], check=True)
    subprocess.run(["git", "-C", git_local_path, "add", "-A"], check=True)
    subprocess.run(
        ["git", "-C", git_local_path, "commit", "-m", f"Auto-fix: {diff_summary}"],
        check=True,
    )
    subprocess.run(
        ["git", "-C", git_local_path, "push", "-u", "origin", branch_name],
        check=True,
    )

    # Open the PR via GitHub REST API
    api_url = f"https://api.github.com/repos/{github_repo}/pulls"
    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
    }
    body = {
        "title": f"[drift-agent] {diff_summary}",
        "head": branch_name,
        "base": base_branch,
        "body": (
            f"**Auto-generated by the drift remediation agent**\n\n"
            f"**What changed:** {diff_summary}\n\n"
            f"**Why this was classified as safe:** {reasoning}\n\n"
            f"Review before merging -- this was classified safe by an LLM, not guaranteed correct."
        ),
    }
    resp = requests.post(api_url, headers=headers, json=body, timeout=30)
    resp.raise_for_status()
    return resp.json()["html_url"]


def send_slack_alert(diff_summary: str, reasoning: str, raw_diff: str, webhook_url: str) -> None:
    text = (
        f":rotating_light: *Risky drift detected in Kubernetes cluster*\n\n"
        f"*What changed:* {diff_summary}\n"
        f"*Why it's flagged risky:* {reasoning}\n\n"
        f"```{raw_diff[:1500]}```\n"
        f"_This was NOT auto-applied. Please review manually._"
    )
    resp = requests.post(webhook_url, json={"text": text}, timeout=15)
    resp.raise_for_status()
