apiVersion: v1
kind: Service
metadata:
  name: drift-demo
  namespace: default
  labels:
    app: drift-demo
spec:
  selector:
    app: drift-demo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
